# PHPコードを強制的に自動整形します。
# このワークフローは、develop, staging, mainブランチに対してのプルリクエストのみ実行されます。
# .php-cs-fixer.dist.php が存在する場合は、その設定を使用します。
# サポートするPHPのバージョンは、8以上です。
# このワークフローは、main.yml によって実行されることを想定しています。
name: PHPコード整形

on:
  workflow_call:

defaults:
  run:
    working-directory: ./src

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: .php-cs-fixer.dist.php が存在するか確認
        id: fixer-check
        run: test -f .php-cs-fixer.dist.php && echo "::set-output name=exists::true" || exit 0

      - name: PHP 8.0をインストール
        if: steps.fixer-check.outputs.exists == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - name: PHP-CS-Fixerをインストール
        if: steps.fixer-check.outputs.exists == 'true'
        run: composer global require friendsofphp/php-cs-fixer

      - name: PHPコードを自動整形 (dry-run)
        id: fixer-dry-run
        if: steps.fixer-check.outputs.exists == 'true'
        run: php ~/.composer/vendor/bin/php-cs-fixer fix --verbose --diff --dry-run --config=.php-cs-fixer.dist.php || true

      - name: PHPコードを自動整形
        if: steps.fixer-check.outputs.exists == 'true' && env.CHANGED == '0'
        run: |
          php ~/.composer/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php
          git status | grep modified || echo "GIT_STATUS_RESULT=$(echo $?)" >> $GITHUB_ENV

      - name: 変更がある場合は、自動整形したコードをコミット
        if: env.GIT_STATUS_RESULT == '0'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -a -m "PHPコードを自動整形"
          git push
