# 常に実行します。
# 作業内容は、format.yml を呼び出し、実行します。
name: メインアクション

on:
  pull_request:
  workflow_dispatch:

jobs:
  main:
    concurrency: main
    # main は、何もしない
    runs-on: ubuntu-latest
    steps:
      - name: "main action"
        run: echo "actions start"
      - name: "github.event_name"
        # このアクションは、 github.event_name を 表示
        run: echo ${{ github.event_name }}
      - name: "github.head_ref"
        # このアクションは、 github.head_ref を 表示
        run: echo ${{ github.head_ref }}
      - name: "github.base_ref"
        # このアクションは、 どのブランチに pull request があったかを 表示
        run: echo ${{ github.base_ref }}
      - name: "main end"
        run: echo "actions end"

  call-workflow:
    # develop, staging, mainブランチ に pull request があった場合に実行します。
    # 同一ディレクトリにある format.yml を呼び出し、実行する
    if: github.event_name == 'pull_request' && (github.base_ref == 'develop' || github.base_ref == 'staging' || github.base_ref == 'main')
    needs: [main]
    uses: ./.github/workflows/format.yml
